# Generated by Django 3.0.2 on 2020-01-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('sales_manager', models.TextField()),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('headquarter', models.TextField(null=True)),
                ('current_employees', models.IntegerField()),
                ('isPartner', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('storage', models.PositiveIntegerField(help_text='in GB')),
                ('isEnterpriseModel', models.BooleanField()),
                ('selled_at', models.ManyToManyField(blank=True, to='computermanager.Shop')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computermanager.Vendor')),
            ],
        ),
    ]
