# Generated by Django 3.0.2 on 2020-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='selled_at',
        ),
        migrations.AddField(
            model_name='computer',
            name='sold_at',
            field=models.ManyToManyField(blank=True, related_name='computers', to='computermanager.Shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='current_sale',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='current_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
            preserve_default=False,
        ),
    ]
