# Generated by Django 3.0.2 on 2020-01-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computermanager', '0002_auto_20200108_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='current_sale',
            new_name='current_sales',
        ),
    ]
