# Generated by Django 3.0.2 on 2020-01-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermanager', '0003_auto_20200108_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.TextField(default='NiceComputers'),
            preserve_default=False,
        ),
    ]
