# Generated by Django 3.0.2 on 2020-01-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermanager', '0004_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='current_sales',
            field=models.FloatField(),
        ),
    ]
